/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface KnativeServiceSpec {
  apiVersion: "serving.knative.dev/v1alpha1";
  kind: "Service";
  metadata: {
    name: string;
    namespace: string;
    labels: {
      "serving.knative.dev/visibility": "cluster-local";
    };
    annotations: {
      manifestHash: string;
    };
  };
  spec: {
    template: {
      metadata: {
        annotations: {
          "io.kubernetes.cri.untrusted-workload": "true";
        };
      };
      spec: {
        serviceAccountName: string;
        containers: {
          name?: string;
          image: string;
          command?: string[];
          workingDir?: string;
          resources: {
            limits: {
              memory: string;
              cpu: string;
            };
          };
          ports?: {
            containerPort?: number;
          }[];
          env?: {
            name?: string;
            value?: string;
          }[];
        }[];
      };
    };
  };
}
