/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PodSpec {
  apiVersion: string;
  kind: string;
  metadata: {
    name: string;
    namespace: string;
  };
  spec: {
    automountServiceAccountToken: boolean;
    containers: {
      name?: string;
      image: string;
      command?: string[];
      workingDir?: string;
      resources: {
        limits: {
          memory: string;
          cpu: string;
        };
      };
      env?: {
        name?: string;
        value?: string;
      }[];
    }[];
    dnsPolicy: string;
    runtimeClassName: string;
  };
}
